apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ui-config
data:
  mysql.host: mysql
  mysql.port: "3306"
  mysql.usr: root
  mysql.pwd: "{{db_password}}"
  registry.url: http://registry:5000
  config.path: /etc/ui/app.conf
  harbor.reg.url: "{{hostname}}"
  harbor.admin.password: "{{harbor_admin_password}}"
  harbor.url: http://ui
  auth.mode: "{{auth_mode}}"
  ldap.url: "{{ldap_url}}"
  ldap.search.dn: "{{ldap_searchdn}}"
  ldap.search.pwd: "{{ldap_search_pwd}}"
  ldap.base.dn: "{{ldap_basedn}}"
  ldap.filter: "{{ldap_filter}}"
  ldap.uid: "{{ldap_uid}}"
  ldap.scope: "{{ldap_scope}}"
  log.level: debug
  ui.secret: "{{ui_secret}}"
  secret.key: "{{secret_key}}"
  godebug: netdns=cgo
  ext.endpoint: "{{ui_url}}"
  token.url: http://ui
  self.registration: "{{self_registration}}"
  use.compressed.js: "{{use_compressed_js}}"
  verify.remote.cert: "{{verify_remote_cert}}"
  token.expiration: "{{token_expiration}}"
  ext.reg.url: "{{hostname}}"
  config: |
    appname = registry
    runmode = dev
    [lang]
    types = en-US|zh-CN
    names = en-US|zh-CN
    [dev]
    httpport = 80
    [mail]
    host = {{email_server}}
    port = {{email_server_port}}
    username = {{email_username}}
    password = {{email_password}}
    from = {{email_from}}
    ssl = {{email_ssl}}
  pkey: |
    {{4 auth_pkey}}


