apiVersion: v1
kind: ReplicationController
metadata:
  name: jobservice-rc
  labels:
    name: jobservice-rc
spec:
  replicas: 1
  selector:
    name: jobservice-apps
  template:
    metadata:
      labels:
        name: jobservice-apps
    spec:
      containers:
      - name: jobservice-app
        image: vmware/harbor-jobservice:0.5.0
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_HOST
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: mysql.host
          - name: MYSQL_PORT
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: mysql.port
          - name: MYSQL_USR
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: mysql.usr
          - name: MYSQL_PWD
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: mysql.pwd
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: ui.secret
          - name: SECRET_KEY
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: secret.key
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: config.path
          - name: REGISTRY_URL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: registry.url
          - name: VERIFY_REMOTE_CERT
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: verify.remote.cert
          - name: MAX_JOB_WORKERS
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: max.job.workers
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: log.level
          - name: LOG_DIR
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: log.dir
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: godebug
          - name: EXT_ENDPOINT
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: ext.endpoint
          - name: TOKEN_URL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: token.url
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/jobservice
        - name: logs
          mountPath: /var/log/jobs
      volumes:
      - name: config
        configMap:
          name: harbor-jobservice-config
          items:
          - key: config
            path: app.conf
      - name: logs
        persistentVolumeClaim:
          claimName: log-pvc 
      nodeSelector:
        hostname: cu3