apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  mysql.host: mysql
  mysql.port: "3306"
  mysql.usr: root
  mysql.pwd: "{{db_password}}"
  ui.secret: "{{ui_secret}}"
  secret.key: "{{secret_key}}"
  config.path: /etc/jobservice/app.conf
  registry.url: http://registry:5000
  verify.remote.cert: "{{verify_remote_cert}}"
  max.job.workers: "{{max_job_workers}}"
  log.level: debug
  log.dir: /var/log/jobs
  godebug: netdns=cgo
  ext.endpoint: "{{ui_url}}"
  token.url: http://ui
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
