apiVersion: v1
kind: ConfigMap
metadata:
  name: dta-bin-config
data:

  bootstrap: |
    #!/bin/sh
    
    rm -rf /etc/localtime ; ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime ;
    ln -s /opt/bin/hadoop.profile /etc/profile.d/hadoop.sh ;
    ln -s /opt/bin/hadoop.limits /etc/security/limits.d/hadoop.conf ;
    chown -R hadoop:hadoop /data
    chmod 700 /data;
    chmod 700 /data/bigdata;
    
    gosu hadoop:hadoop sh /opt/bin/startup "$@" 


  hadoop.limits: |
    * - nofile 128000
    * - nproc  65536
    * - memlock 8000000000


  hadoop.profile: |
    export JAVA_HOME=/opt/jdk1.8.0_121
    export HADOOP_HOME=/opt/hadoop-2.6.5
    export HADOOP_USER_NAME=hadoop
    
    export PATH=$HADOOP_HOME/bin:$JAVA_HOME/bin:$PATH


  startup: |
    #!/bin/sh
    
    # 
    mkdir -p /data/bigdata/pids
    mkdir -p /data/bigdata/hadoop
    chmod 700 /data/bigdata/hadoop
    
    # share 
    rm -rf /opt/hadoop-2.6.5/logs
    mkdir -p /data/bigdata/logs
    ln -s /data/bigdata/logs /opt/hadoop-2.6.5/
    
    function check(){
      APP="$1"
      ps aux|grep java|grep -i "$APP"
      return $?
    }
    
    function checkAll(){
      times=36
      while ((times>0)) ; do
        echo -n '.' 
        sleep 11;
        for app in "$@" ; do
          if ! check "$app" ; then
            ((times--))
            continue 2
          fi
        done
        times=11
      done
    
    }
    
    function master(){
      cd /opt/hadoop-2.6.5
    
      bin/hdfs namenode -format
      
      sbin/hadoop-daemon.sh start namenode
      sbin/yarn-daemon.sh start resourcemanager
      checkAll NameNode ResourceManager
    }
    
    function slaver(){
      cd /opt/hadoop-2.6.5
    
      sbin/hadoop-daemon.sh start datanode
      sbin/yarn-daemon.sh start nodemanager
      checkAll DataNode NodeManager
    }
    
    case "$1" in 
      m|master|Master) 
        master
        ;;
      s|slaver|Slaver) 
        slaver
        ;;
      *) 
        echo "`basename ${0}`:usage: Master | Slaver"
        exit 1
        ;;
    esac
