apiVersion: v1
kind: ReplicationController
metadata:
  name: slaver-rc
  labels:
    name: slaver-rc
spec:
  replicas: 2
  selector:
    name: slaver-apps
  template:
    metadata:
      labels:
        name: slaver-apps
        cluster: dta
    spec:
      containers:
      - name: slaver-app
        image: cu.eshore.cn/library/hadoop:root
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "1"
            memory: 512Mi
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - rm -rf /etc/localtime ; ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime ;
                chown hadoop:hadoop /data ; chmod 700 /data; 
                ln -s /opt/bin/hadoop.profile /etc/profile.d/hadoop.sh ;
                ln -s /opt/bin/hadoop.limits /etc/security/limits.d/hadoop.conf ;
        command: ["bash", "-c"]
        args:
        - chmod +x /opt/bin/bootstrap;
          gosu hadoop:hadoop /opt/bin/bootstrap Slaver; 
        env:
          - name: TERM
            value: xterm
          - name: USER
            value: hadoop
        volumeMounts:
        - name: config
          mountPath: /opt/hadoop-2.6.5/etc/hadoop
        - name: bin
          mountPath: /opt/bin
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: dta-hadoop-config
      - name: bin
        configMap:
          name: dta-bin-config
      - name: data
        emptyDir: {}
