apiVersion: v1
kind: ReplicationController
metadata:
  name: slaver-rc
  labels:
    name: slaver-rc
spec:
  replicas: 2
  selector:
    name: slaver-apps
  template:
    metadata:
      labels:
        name: slaver-apps
        cluster: dta
    spec:
      containers:
      - name: slaver-app
        image: cu.eshore.cn/library/hadoop:2.6.5
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "1"
            memory: 512Mi
        command: ["bash", "-c"]
        args: 
        - chmod +x /opt/bin/bootstrap;
          /opt/bin/bootstrap slaver
        env:
          - name: TERM
            value: xterm
          - name: USER
            value: hadoop
        volumeMounts:
        - name: config
          mountPath: /opt/hadoop-2.6.5/etc/hadoop
        - name: bin
          mountPath: /opt/bin
        - name: data
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: dta-hadoop-config
      - name: bin
        configMap:
          name: dta-bin-config
      - name: data
        emptyDir: {}
