apiVersion: v1
kind: Pod
metadata:
  name: hadoop-master2
  labels:
    name: hadoop-master2
    cluster: dta
spec:
  containers:
  - name: hadoop-master2
    image: cu.eshore.cn/library/hadoop:2.6.5
    imagePullPolicy: IfNotPresent
    command: ["bash", "-c"]
    args: 
    - chmod +x /opt/bin/bootstrap;
      /opt/bin/bootstrap master
    env:
      - name: TERM
        value: xterm
      - name: USER
        value: hadoop
    volumeMounts:
    - name: config
      mountPath: /opt/hadoop-2.6.5/etc/hadoop
    - name: bin
      mountPath: /opt/bin
    - name: data
      mountPath: /data
  volumes:
  - name: config
    configMap:
      name: dta-hadoop-config
  - name: bin
    configMap:
      name: dta-bin-config
  - name: data
    emptyDir: {}
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-master2
spec:
  selector:
    name: hadoop-master2
  clusterIP: None
  ports:
  - name: dfs-namenode-service
    port: 9000
  - name: dfs-namenode-http-address
    port: 50070
  - name: dfs-journalnode-rpc-address
    port: 8485
  - name: dfs-journalnode-http-address
    port: 8480
  - name: yarn-resourcemanager-address
    port: 8032
  - name: yarn-resourcemanager-scheduler-address
    port: 8030
  - name: yarn-resourcemanager-resource-tracker-address
    port: 8031
  - name: yarn-resourcemanager-admin-address
    port: 8033
  - name: mapreduce-jobhistory-admin-address
    port: 10033
  - name: mapreduce-jobhistory-address
    port: 10020
  - name: mapreduce-jobhistory-webapp-address
    port: 19888
