apiVersion: v1
kind: Pod
metadata:
  name: zeppelin
  labels:
    name: zeppelin
    cluster: dta
spec:
  containers:
  - name: zeppelin
    image: cu.eshore.cn/library/zeppelin:0.7.1
    imagePullPolicy: IfNotPresent
    command: ["bash", "-c"]
    args: 
    - /opt/zeppelin-0.7.1/bin/zeppelin-daemon.sh upstart
    env:
      - name: TERM
        value: xterm
      - name: USER
        value: hadoop
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    emptyDir: {}
  restartPolicy: Never
