apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel-rc
  labels:
    name: redis-sentinel-rc
spec:
  replicas: 3
  selector:
    name: redis-sentinel-apps
  template:
    metadata:
      labels:
        name: redis-sentinel-apps
    spec:
      containers:
      - name: redis-sentinel-app
        image: cu.eshore.cn/library/codis:3.2
        imagePullPolicy: IfNotPresent
        command:
        - codis-server 
        - "/etc/redis/sentinel.conf"
        - "--dir"
        - "/data/redis"
        - "--protected-mode"
        - "no"
        - "--sentinel"
        volumeMounts:
        - name: redis-storage
          mountPath: /data/redis
        - name: redis-conf
          mountPath: /etc/redis
      volumes:
      - name: redis-storage
        emptyDir: {}
      - name: redis-conf
        hostPath: 
          path: /data/redis
