# https://hub.docker.com/r/library/registry/
# https://docs.docker.com/registry/#requirements
# https://docs.docker.com/registry/deploying/#running-a-domain-registry
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
      volumes:
      - name: registry-storage
        hostPath:
          path: /data/registry
      nodeSelector:
        hostname: cu1
---
apiVersion: v1
kind: Service
metadata: 
  name: registry-service
  labels: 
    app: registry
spec: 
  ports:
    - port: 6000
      targetPort: 5000
  selector: 
    app: registry