# https://github.com/sonatype/docker-nexus
apiVersion: v1
kind: Pod
metadata:
  name: nexus
spec:
  hostNetwork: true
  containers:
  - name: nexus
    image: sonatype/nexus:oss
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8081
    volumeMounts:
    - name: nexus-storage
      mountPath: /sonatype-work
    env:
    - name: CONTEXT_PATH
      value: /nexus
    - name: MAX_HEAP
      value: 256m
    - name: MIN_HEAP
      value: 256m
  volumes:
  - name: nexus-storage
    hostPath:
      path: /data/nexus
  nodeSelector:
    hostname: cu1