apiVersion: v1
kind: Pod
metadata:
  name: hadoop-slaver1
  labels:
    name: hadoop-slaver1
    cluster: dta
spec:
  containers:
  - name: hadoop-slaver1
    image: cu.eshore.cn/library/hadoop:root
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - bash
          - -c
          - rm -rf /etc/localtime ; ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime ;
            ln -s /opt/bin/hadoop.profile /etc/profile.d/hadoop.sh ;
            ln -s /opt/bin/hadoop.limits /etc/security/limits.d/hadoop.conf ;
    command: ["bash", "-c"]
    args:
    - chmod +x /opt/bin/bootstrap ;
      /usr/sbin/sshd -D;
      #gosu hadoop:hadoop /opt/bin/bootstrap Slaver; 
    env:
      - name: TERM
        value: xterm
      - name: USER
        value: hadoop
    volumeMounts:
    - name: config
      mountPath: /opt/hadoop-2.6.5/etc/hadoop
    - name: bin
      mountPath: /opt/bin
    - name: data
      mountPath: /data
  volumes:
  - name: config
    configMap:
      name: dta-hadoop-config
  - name: bin
    configMap:
      name: dta-bin-config
  - name: data
    emptyDir: {}
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-slaver1
spec:
  selector:
    name: hadoop-slaver1
  clusterIP: None
  ports:
  - name: dfs-datanode-address
    port: 50010
  - name: dfs-datanode-http-address
    port: 50075
  - name: dfs-datanode-ipc-address
    port: 50020
