apiVersion: v1
kind: ReplicationController
metadata:
  name: slaver-rc
  labels:
    name: slaver-rc
spec:
  replicas: 3
  selector:
    name: slaver-apps
  template:
    metadata:
      labels:
        name: slaver-apps
        cluster: dta
    spec:
      containers:
      - name: slaver-app
        image: cu.eshore.cn/library/hbase:1.3.1
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args: 
        - chmod +x /opt/bin/*;
          /opt/bin/bootstrap slaver;
          /opt/bin/alive DataNode NodeManager RegionServer;
        env:
          - name: TERM
            value: xterm
          - name: USER
            value: hadoop
        volumeMounts:
        - name: hadoopconfig
          mountPath: /opt/conf/hadoop
        - name: hbaseconfig
          mountPath: /opt/conf/hbase
        - name: bin
          mountPath: /opt/bin
        - name: data
          mountPath: /data
      volumes:
      - name: hadoopconfig
        configMap:
          name: dta-hadoop-config
      - name: hbaseconfig
        configMap:
          name: dta-hbase-config
      - name: bin
        configMap:
          name: dta-bin-config
      - name: data
        emptyDir: {}
