# https://github.com/sonatype/docker-nexus
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      hostNetwork: true
      containers:
      - name: nexus
        image: sonatype/nexus:oss
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8081
        volumeMounts:
        - name: nexus-storage
          mountPath: /sonatype-work
        env:
        - name: CONTEXT_PATH
          value: /nexus
        - name: MAX_HEAP
          value: 1024m
        - name: MIN_HEAP
          value: 1024m
      volumes:
      - name: nexus-storage
        hostPath:
          path: /data/nexus
      nodeSelector:
        hostname: cu1